### ISSUE TITLE
The client crashes when trying to open a closed file with ALT + F4

### ISSUE THREAD

**Issue by emancus** [giovannic96/Real-time-collaborative-text-editor#71]
![issue](https://user-images.githubusercontent.com/55850895/70390794-a7f48a00-19ce-11ea-891d-2e3489325949.png)

Application Output [Client-side]

**Comment by giovannic96** [comment]
ALT-F4 is a forced quit. This means that we don't have to display a message popup saying "do you want to close the file?" because is a forced quit, used if there are any problems. Maybe we can handle this by saving current updates of the file and close, without informing the user. 

Neverthless, this issue remains and we have to solve this

**Comment by giovannic96** [comment]
@HidroSaphire I think you implemented the popup message

**Comment by emancus** [comment]
@giovannic96 yes, I've handle the ALT+F4 combo in this way:
- In the Editor = popup message
- In the other window = force closed

**Comment by emancus** [comment]
I have tried several times. Since I redefined the closing event of the program, crashes no longer occur.
I close this issue.
